### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Nhawdge** [Nhawdge/takeover#1]
- [x] improved attacks 
- [x] multiple node types
- [x] static levels
  - [x] xml level save
  - [x] xml level load
- [x] improved art 
- [x] animations
- [x] campaign
- [x] Mac release
- [x] Linux release
- [x] leader boards
- [x] seed entry/deterministic level generation
- [x] zip assets in release
- [x] barriers and walls
- [x] maybe switches and gates?
